wandb_key : "a967166cb6f5f15eefe606cee45c0b6a185c2174"

# ALS model hyperparameters and configuration settings
# ALS hyperparameters were selected through Cross-Validation in ..src/tests/als/ALS_hyperparam_optimization.ipynb

ALS_CONFIG : {
    "rank": 40,               # Number of latent factors
    "max_iter": 15,           # Number of iterations to run the optimization
    "reg_param": 0.1,         # Regularization parameter
    "implicit_prefs": True,   # If True, ALS will use implicit feedback
    "alpha": 1.0,             # Confidence parameter (only relevant if implicit_prefs=True)
    "cold_start_strategy": "drop",  # Strategy to handle cold-start users/items
    "model_save_path": "saved_models/als_model",
}

DATASET_CONFIG : {
    "size": "small",            # Dataset size: "demo", "small", or "large"
    "npratio": 4,              # Negative sampling ratio for training. Adjust this ratio based on class imbalance requirements # Path to store MIND datasets
}


TRAIN_TEST_SPLIT : {
    "train_ratio": 0.8,  
    "seed": 47,          
}

# Evaluation metrics
EVAL_CONFIG : {
    "k": 10,  # Number of recommendations for evaluation
}

services: 
  als:
    enabled : false
  cbrs:
    enabled : true